# Generated by Django 6.0.4 on 2026-06-04 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='lignecommande',
            options={'verbose_name': 'Ligne de commande', 'verbose_name_plural': 'Lignes de commande'},
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(blank=True, default='', help_text='Obligatoire si type_commande = livraison.', verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_nom',
            field=models.CharField(blank=True, default='', help_text='Requis pour une livraison.', max_length=100, verbose_name='Nom du client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='commande',
            name='note_cuisine',
            field=models.TextField(blank=True, default='', help_text='Instructions spéciales : cuisson, allergies, modifications...', verbose_name='Note pour la cuisine'),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_table',
            field=models.CharField(blank=True, help_text='Ex: 03, VIP-1. Laisser vide pour une livraison.', max_length=10, null=True, verbose_name='Numéro de table'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total (FCFA)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='serveur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Serveur'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('servie', 'Servie'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type_commande',
            field=models.CharField(choices=[('sur_place', 'Sur place'), ('livraison', 'Livraison')], default='sur_place', max_length=20, verbose_name='Type de commande'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
    ]
