# Generated by Django 6.0.4 on 2026-06-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_commande_options_alter_lignecommande_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('servie', 'Servie'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type_commande',
            field=models.CharField(choices=[('sur_place', 'Sur place'), ('livraison', 'Livraison'), ('a_emporter', 'A emporter')], default='sur_place', max_length=20, verbose_name='Type de commande'),
        ),
    ]
