# Generated by Django 6.0.4 on 2026-05-29 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('directeur', 'Directeur'), ('administrateur', 'Administrateur'), ('chef_cuisinier', 'Chef cuisinier'), ('cuisinier', 'Cuisinier'), ('serveur', 'Serveur'), ('responsable_stock', 'Responsable stock'), ('caissier', 'Caissier'), ('livreur', 'Livreur')], max_length=30)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_embauche', models.DateField()),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel',
                'ordering': ['poste'],
            },
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('jours_travailles', models.PositiveIntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('versee', 'Versée')], default='en_attente', max_length=15)),
                ('date_versement', models.DateField(blank=True, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paies', to='rh.personnel')),
            ],
            options={
                'verbose_name': 'Paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('personnel', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('remarque', models.CharField(blank=True, max_length=200, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='rh.personnel')),
            ],
            options={
                'verbose_name': 'Présence',
                'ordering': ['-date'],
                'unique_together': {('personnel', 'date')},
            },
        ),
    ]
