# Generated by Django 4.2.11 on 2026-06-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paie',
            options={'ordering': ['-annee', '-mois'], 'verbose_name': 'Paie', 'verbose_name_plural': 'Paies'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['poste'], 'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnels'},
        ),
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-date'], 'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('directeur', 'Directeur'), ('administrateur', 'Administrateur'), ('chef_cuisinier', 'Chef cuisinier'), ('cuisinier', 'Cuisinier'), ('serveur', 'Serveur'), ('responsable_stock', 'Gestionnaire de stock'), ('caissier', 'Caissier'), ('livreur', 'Livreur')], max_length=30),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('salle', 'Service en salle'), ('cuisine', 'Cuisine'), ('accueil', 'Accueil'), ('stock', 'Stock et approvisionnement')], max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='rh.personnel')),
            ],
        ),
    ]
