# Generated by Django 4.2.11 on 2026-06-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('directeur', 'Directeur'), ('chef_cuisinier', 'Chef cuisinier'), ('cuisinier', 'Cuisinier'), ('serveur', 'Serveur'), ('responsable_stock', 'Gestionnaire de stock'), ('client', 'Client'), ('caissier', 'Caissier'), ('livreur', 'Livreur')], default='client', max_length=30, verbose_name='Rôle'),
        ),
    ]
