# Generated by Django 6.0.4 on 2026-05-15 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("unite", models.CharField(max_length=50)),
                ("seuil_critique", models.FloatField(default=0)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Ingrédient",
                "verbose_name_plural": "Ingrédients",
            },
        ),
        migrations.CreateModel(
            name="Recette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("temps_cuisson", models.IntegerField(help_text="Temps en minutes")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "chef_responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recettes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recette",
                "verbose_name_plural": "Recettes",
            },
        ),
        migrations.CreateModel(
            name="RecetteIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.FloatField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recettes.ingredient",
                    ),
                ),
                (
                    "recette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recettes.recette",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrédient de recette",
                "verbose_name_plural": "Ingrédients de recette",
            },
        ),
        migrations.AddField(
            model_name="recette",
            name="ingredients",
            field=models.ManyToManyField(
                through="recettes.RecetteIngredient", to="recettes.ingredient"
            ),
        ),
    ]
