# Generated by Django 6.0.4 on 2026-06-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
