# Generated by Django 6.0.4 on 2026-06-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_produit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
