# Generated by Django 4.2.11 on 2026-06-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_recette_instructions'),
        ('produits', '0003_alter_produit_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image_url',
        ),
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='recettes.recette'),
        ),
    ]
